// ─── Quote Automation ─────────────────────────────────────────────────────────
import { todayISO, genId } from "./helpers";
import { offlineSave } from "../offline/offlineDb";
import { triggerImmediateSync } from "./sync";
import { withTeamId } from "./teamId";
import { createJobFromAcceptedQuote } from "./jobInvoiceAutomation";
function addBusinessDays(dateStr,days){const d=new Date(`${dateStr}T12:00:00`);let n=0;while(n<days){d.setDate(d.getDate()+1);if(d.getDay()!==0&&d.getDay()!==6)n++}return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
export function autoCreateChaseFollowup(quote,userId,setData,teamId=null,existing=[]){if(!quote?.id||!userId||existing.some(x=>x.quote_id===quote.id&&x.auto_generated))return null;const item=withTeamId({id:genId(),user_id:userId,client_id:quote.client_id||null,client:quote.client_name||"",branch:"",title:`Chase quote: ${(quote.description||"").slice(0,60)}`,date:addBusinessDays(quote.sent_date||todayISO(),3),time:"09:00",reminder:"morning",notes:`Auto-created: follow up on quote (${quote.description||""}) — R ${parseFloat(quote.value||0).toLocaleString("en-ZA")}`,completed:false,auto_generated:true,quote_id:quote.id,created_at:new Date().toISOString(),sync_status:"pending"},teamId);setData(d=>({...d,followups:[item,...(d.followups||[])],syncQueue:[{id:genId(),table:"followups",action:"insert",data:item,status:"pending",created_at:new Date().toISOString()},...(d.syncQueue||[])]}));offlineSave("followups",item).then(()=>triggerImmediateSync());if(quote.status==="Accepted")createJobFromAcceptedQuote(quote,userId,teamId,setData,typeof navigator==="undefined"?true:navigator.onLine).catch(e=>console.warn("Quote→job creation failed:",e));return item}
export function autoAdvanceOnAccept(quote,clients,setData){if(!quote?.client_name)return;const c=(clients||[]).find(x=>x.company&&x.company.toLowerCase()===quote.client_name.toLowerCase());if(c&&c.stage!=="Won"&&c.stage!=="Active"){const u={...c,stage:"Active",sync_status:"pending"};setData(d=>({...d,clients:(d.clients||[]).map(x=>x.id===c.id?u:x),syncQueue:[{id:genId(),table:"clients",action:"update",data:u,status:"pending",created_at:new Date().toISOString()},...(d.syncQueue||[])]}));offlineSave("clients",u).then(()=>triggerImmediateSync())}createJobFromAcceptedQuote(quote,quote.user_id,quote.team_id||null,setData,typeof navigator==="undefined"?true:navigator.onLine).catch(e=>console.warn("Quote→job creation failed:",e))}
export function autoExpireStaleQuotes(quotes,setData,userId){const cutoffDate=new Date(`${todayISO()}T12:00:00`);cutoffDate.setDate(cutoffDate.getDate()-14);const cutoff=`${cutoffDate.getFullYear()}-${String(cutoffDate.getMonth()+1).padStart(2,"0")}-${String(cutoffDate.getDate()).padStart(2,"0")}`;const updates=(quotes||[]).filter(q=>q.status==="Pending"&&q.user_id===userId&&(q.sent_date||q.created_at?.slice(0,10)||"")<cutoff).map(q=>({...q,status:"Expired",sync_status:"pending"}));if(!updates.length)return;setData(d=>({...d,quotes:(d.quotes||[]).map(q=>updates.find(u=>u.id===q.id)||q),syncQueue:[...updates.map(u=>({id:genId(),table:"quotes",action:"update",data:u,status:"pending",created_at:new Date().toISOString()})),...(d.syncQueue||[])]}));updates.forEach(u=>offlineSave("quotes",u));triggerImmediateSync()}
export async function ensureAcceptedQuotesHaveJobs(quotes,userId,teamId=null,setData=null,isOnline=typeof navigator==="undefined"?true:navigator.onLine){const results=[];for(const q of(quotes||[]).filter(q=>q.status==="Accepted"&&q.user_id===userId))results.push(await createJobFromAcceptedQuote(q,userId,teamId,setData,isOnline));return results}
export function runQuoteAutomations(data,setData,userId,teamId=null){if(!userId)return;const quotes=data.quotes||[],followups=data.followups||[],online=typeof navigator==="undefined"?true:navigator.onLine;autoExpireStaleQuotes(quotes,setData,userId);quotes.filter(q=>q.user_id===userId&&q.sent_date&&["Pending","Accepted"].includes(q.status)).forEach(q=>autoCreateChaseFollowup(q,userId,setData,teamId,followups));quotes.filter(q=>q.user_id===userId&&q.status==="Accepted").forEach(q=>autoAdvanceOnAccept(q,data.clients||[],setData));ensureAcceptedQuotesHaveJobs(quotes,userId,teamId,setData,online).catch(e=>console.warn("Quote→job automation failed:",e))}
