// ─── PowerMate Sync Engine ───────────────────────────────────────────────────
// Durable offline queue + dependency-safe reconciliation + realtime protection.
import { supabase } from "../supabase";
import { logEvent } from "./helpers";
import { offlineSave, offlineDelete, offlineGetAll, offlineReplaceAll } from "../offline/offlineDb";
import { logCrash } from "../components/ErrorBoundary";

const SYNC_TABLES=["clients","followups","quotes","contacts","notes","equipment","expenses","leads","vehicle_checks","activities","breakdown_reports","repair_reports","custom_faults","service_reports","team_notifications","jobs","invoices","payments"];
const TEAM_TABLES=new Set(["clients","followups","quotes","contacts","notes","equipment","leads","activities","breakdown_reports","repair_reports","custom_faults","service_reports","jobs","invoices","payments"]);
const LOCAL_STORE={breakdown_reports:"breakdowns",repair_reports:"repairs",custom_faults:"customFaults",service_reports:"serviceReports",team_notifications:"teamNotifications"};
const localStoreName=table=>LOCAL_STORE[table]||table;
const MAX_SYNC_ATTEMPTS=8,PAGE_SIZE=1000,RECONCILE_MS=30000;
let _syncInProgress=false,_globalSetData=null,_globalQueueRef=null;

const REMOTE_EXCLUDED_FIELDS={quotes:new Set(["contact_id","from_user_id","to_user_id","job_id","invoice_id"]),followups:new Set(["invoice_id","job_id"])};
const DEPENDENCIES={followups:[{field:"quote_id",pending:"sync_pending_quote_id",table:"quotes"},{field:"client_id",pending:"sync_pending_client_id",table:"clients"},{field:"linked_note_id",pending:"sync_pending_note_id",table:"notes"},{field:"team_id",pending:"sync_pending_team_id",table:"teams"}],jobs:[{field:"quote_id",pending:"sync_pending_quote_id",table:"quotes"},{field:"client_id",pending:"sync_pending_client_id",table:"clients"}],invoices:[{field:"quote_id",pending:"sync_pending_quote_id",table:"quotes"},{field:"job_id",pending:"sync_pending_job_id",table:"jobs"},{field:"client_id",pending:"sync_pending_client_id",table:"clients"}],payments:[{field:"invoice_id",pending:"sync_pending_invoice_id",table:"invoices"}]};
const SYNC_PRIORITY={clients:10,quotes:20,contacts:30,notes:30,equipment:30,expenses:30,leads:30,vehicle_checks:30,activities:30,breakdown_reports:30,repair_reports:30,custom_faults:30,service_reports:30,team_notifications:30,followups:40,jobs:50,invoices:60,payments:70};
function sanitizeRemotePayload(table,data){const out={...(data||{})};for(const field of REMOTE_EXCLUDED_FIELDS[table]||[])delete out[field];return out;}
function cleanUUIDs(data){const fields=["id","user_id","team_id","client_id","contact_id","linked_note_id","linked_breakdown_id","assigned_to_user_id","from_user_id","to_user_id","quote_id","job_id","invoice_id","sync_pending_quote_id","sync_pending_job_id","sync_pending_client_id","sync_pending_note_id","sync_pending_team_id","sync_pending_invoice_id"];const out={...(data||{})};fields.forEach(f=>{if(out[f]===""||out[f]===undefined)out[f]=null;});return out;}
function cleanNumerics(data){const out={...(data||{})};["estimated_value","value","amount","amount_zar","quote_value","vat_amount","exchange_rate","duration_mins","subtotal","vat","total","amount_paid","balance_due"].forEach(f=>{if(!(f in out))return;const v=out[f];if(v===""||v===undefined)out[f]=null;else if(v!==null&&typeof v==="string"&&Number.isNaN(Number.parseFloat(v)))out[f]=null;});return out;}
function normalizeVehicleCheckPayload(data){const source=data||{};const out={id:source.id,user_id:source.user_id,check_date:source.check_date,vehicle:source.vehicle??null,registration:source.registration??null,driver:source.driver??null,data:source.data??{},sync_status:source.sync_status??"pending",updated_at:source.updated_at??new Date().toISOString()};if(typeof out.data==="string"){try{out.data=JSON.parse(out.data);}catch{out.data={};}}if(!out.id)throw new Error("vehicle_checks record is missing id");if(!out.check_date||!/^[0-9]{4}-[0-9]{2}-[0-9]{2}$/.test(String(out.check_date)))throw new Error("vehicle_checks record has an invalid check_date");return out;}
async function upsertWithSchemaRecovery(table,payload,maxRetries=16){let candidate={...payload};for(let attempt=0;attempt<=maxRetries;attempt++){const{error}=await supabase.from(table).upsert(candidate,{onConflict:"id"});if(!error)return;if(error.code!=="PGRST204")throw error;const match=String(error.message||"").match(/Could not find the '([^']+)' column of '[^']+' in the schema cache/i);const field=match?.[1];if(!field||!(field in candidate))throw error;delete candidate[field];}throw new Error(`Sync schema recovery exhausted for ${table}`);}
async function stageMissingDependencies(table,payload){const deps=DEPENDENCIES[table]||[];if(!deps.length)return payload;let out={...payload};for(const dep of deps){const id=out[dep.field];if(!id||out[dep.pending])continue;const{data,error}=await supabase.from(dep.table).select("id").eq("id",id).maybeSingle();if(!error&&data)continue;if(dep.pending in out){out[dep.pending]=id;out[dep.field]=null;}}return out;}
async function pushOne(table,action,rawData){let payload=sanitizeRemotePayload(table,cleanNumerics(cleanUUIDs(rawData)));if(table==="vehicle_checks")payload=normalizeVehicleCheckPayload(payload);if(payload.media)payload={...payload,media:payload.media.map(m=>({...m,base64:undefined}))};if(["insert","upsert","update"].includes(action)){if(table==="vehicle_checks"){const{data:authData,error:authError}=await supabase.auth.getUser();if(authError)throw authError;if(authData?.user?.id)payload.user_id=authData.user.id;else throw new Error("Cannot sync vehicle check without an authenticated user");}else if(TEAM_TABLES.has(table)&&!payload.user_id){const{data:authData}=await supabase.auth.getUser();if(authData?.user?.id)payload.user_id=authData.user.id;}if(action==="update"&&payload.id){const{data:existing,error:existingError}=await supabase.from(table).select("*").eq("id",payload.id).maybeSingle();if(!existingError&&existing)payload={...existing,...payload};}payload=sanitizeRemotePayload(table,cleanNumerics(cleanUUIDs(payload)));if(table==="vehicle_checks")payload=normalizeVehicleCheckPayload(payload);payload=await stageMissingDependencies(table,payload);await upsertWithSchemaRecovery(table,{...payload,sync_status:"synced"});return;}if(action==="delete"){const{error}=await supabase.from(table).delete().eq("id",payload.id);if(error)throw error;return;}throw new Error(`Unknown sync action: ${action}`);}
export async function pushItem(item){try{const table=item?.table;if(!table||!item?.data)throw new Error("Invalid sync item");await pushOne(table,item.action,item.data);return{ok:true};}catch(error){const detail={code:error?.code,message:error?.message||"Unknown sync error",details:error?.details,hint:error?.hint};console.warn(`[Sync] FAILED ${item?.table} ${item?.action}`,detail);try{logCrash({screen:`Sync (${item?.table} ${item?.action})`,message:`${detail.message}${detail.code?` [${detail.code}]`:""}${detail.details?` — ${detail.details}`:""}`});}catch{}return{ok:false,error:detail};}}
async function persistQueue(queue){await offlineReplaceAll("syncQueue",queue);}
export async function saveAndSync(item,table,action,setData,isOnline){await offlineSave(localStoreName(table),item);const queueItem={id:`sq_${Date.now()}_${Math.random().toString(36).slice(2,8)}`,table,action,data:item,status:"pending",created_at:new Date().toISOString(),attempts:0,next_attempt_at:null};if(isOnline){const result=await pushItem({table,action,data:item});if(result.ok){const synced={...item,sync_status:"synced"};await offlineSave(localStoreName(table),synced);setData(current=>({...current,[localStoreName(table)]:(current[localStoreName(table)]||[]).map(row=>row.id===item.id?synced:row),syncQueue:(current.syncQueue||[]).filter(q=>q.data?.id!==item.id)}));return synced;}}setData(current=>({...current,syncQueue:[queueItem,...(current.syncQueue||[]).filter(q=>!(q.table===table&&q.data?.id===item.id))]}));await offlineSave("syncQueue",queueItem);return{...item,sync_status:"pending"};}
function collapseQueue(queue){const groups=new Map();for(const item of queue){const key=`${item.table}:${item.data?.id}`;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item);}const winners=[],discarded=new Set();for(const[,ops]of groups){ops.sort((a,b)=>new Date(a.created_at||0)-new Date(b.created_at||0));const last=ops[ops.length-1],hasInsert=ops.some(op=>op.action==="insert"),hasDelete=ops.some(op=>op.action==="delete");if(hasInsert&&hasDelete){ops.forEach(op=>discarded.add(op.id));continue;}if(hasDelete)winners.push({...last,action:"delete"});else winners.push({...last,action:hasInsert?"upsert":"update",data:ops.reduce((record,op)=>({...record,...(op.data||{})}),{})});const winner=winners[winners.length-1];ops.forEach(op=>{if(op.id!==winner.id)discarded.add(op.id);});}return{winners,discarded};}
function sortSyncItems(items){return[...items].sort((a,b)=>{const pa=SYNC_PRIORITY[a.table]??100,pb=SYNC_PRIORITY[b.table]??100;if(pa!==pb)return pa-pb;return new Date(a.created_at||0)-new Date(b.created_at||0);});}
function dependencyReady(item,queue){const deps=DEPENDENCIES[item.table]||[];for(const dep of deps){const id=item.data?.[dep.field];if(!id)continue;const parentQueued=queue.some(q=>q.status==="pending"&&q.table===dep.table&&q.data?.id===id&&q.action!=="delete");if(parentQueued)return false;}return true;}
function backoffMs(attempts){return Math.min(60000,1000*Math.pow(2,Math.max(0,attempts-1))+Math.floor(Math.random()*750));}
export async function pushSyncQueue(syncQueue,setData){if(_syncInProgress)return;_syncInProgress=true;try{const now=Date.now();const pending=(syncQueue||[]).filter(item=>item.status==="pending"&&(!item.next_attempt_at||new Date(item.next_attempt_at).getTime()<=now));if(!pending.length)return;const{winners,discarded}=collapseQueue(pending);const queueSnapshot=syncQueue||[];const ordered=sortSyncItems(winners);const outcomes=[];for(const item of ordered){if(!dependencyReady(item,queueSnapshot)){outcomes.push({queueId:item.id,entityId:item.data?.id,table:item.table,action:item.action,ok:false,blocked:true,error:{code:"SYNC_DEPENDENCY_WAIT",message:`Waiting for ${item.table} dependencies`}});continue;}const result=await pushItem(item);outcomes.push({queueId:item.id,entityId:item.data?.id,table:item.table,action:item.action,...result});}const succeeded=outcomes.filter(r=>r.ok),failed=outcomes.filter(r=>!r.ok&&!r.blocked),blocked=outcomes.filter(r=>r.blocked);for(const result of succeeded)if(result.action==="delete")offlineDelete(localStoreName(result.table),result.entityId).catch(()=>{});if(failed.length){logEvent("sync_failed",{count:failed.length});window.dispatchEvent(new CustomEvent("powermate:sync_failed",{detail:{count:failed.length,message:`${failed.length} item${failed.length===1?"":"s"} failed to sync`}}));}if(succeeded.length)logEvent("sync_succeeded",{count:succeeded.length});const succeededIds=new Set(succeeded.map(r=>r.queueId)),failedIds=new Set(failed.map(r=>r.queueId));const nextQueue=(queueSnapshot||[]).filter(item=>!succeededIds.has(item.id)&&!discarded.has(item.id)).map(item=>{if(!failedIds.has(item.id))return item;const attempts=(item.attempts||0)+1;return attempts>=MAX_SYNC_ATTEMPTS?{...item,attempts,status:"failed",last_error:failed.find(r=>r.queueId===item.id)?.error||null}:{...item,attempts,status:"pending",next_attempt_at:new Date(Date.now()+backoffMs(attempts)).toISOString(),last_error:failed.find(r=>r.queueId===item.id)?.error||null};});await persistQueue(nextQueue);setData(current=>{const next={...current,syncQueue:nextQueue};for(const result of succeeded){const key=localStoreName(result.table);if(result.action==="delete")next[key]=(next[key]||[]).filter(row=>row.id!==result.entityId);else if(result.entityId)next[key]=(next[key]||[]).map(row=>row.id===result.entityId?{...row,sync_status:"synced"}:row);}return next;});if(blocked.length&&!failed.length)setTimeout(()=>{if(_globalSetData&&_globalQueueRef)pushSyncQueue(_globalQueueRef.current||[],_globalSetData).catch(()=>{});},1500);}finally{_syncInProgress=false;}}
async function pullAll(makeQuery){const rows=[];for(let page=0;;page+=1){const{data,error}=await makeQuery().range(page*PAGE_SIZE,page*PAGE_SIZE+PAGE_SIZE-1);if(error)return{data:null,error};const batch=data||[];rows.push(...batch);if(batch.length<PAGE_SIZE)return{data:rows,error:null};}}
async function pullTable(table,uid){let query=supabase.from(table).select("*");if(table==="team_notifications")query=query.eq("to_user_id",uid);else if(!TEAM_TABLES.has(table))query=query.eq("user_id",uid);return pullAll(()=>query.order("created_at",{ascending:false}));}
function dirtyQueueForTable(table){return(_globalQueueRef?.current||[]).filter(q=>(q.status==="pending"||q.status==="failed")&&q.table===table);}
export async function pullFromSupabase(uid,setData){if(!uid)return false;try{const results=await Promise.all(SYNC_TABLES.map(table=>pullTable(table,uid))),next={};for(let i=0;i<SYNC_TABLES.length;i++){const table=SYNC_TABLES[i],result=results[i];if(result.error){console.warn(`[Sync] pull failed: ${table}`,result.error);continue;}const local=localStoreName(table),dirty=dirtyQueueForTable(table),localRows=await offlineGetAll(local),dirtyById=new Map(dirty.map(q=>[q.data?.id,q])),serverRows=(result.data||[]).filter(row=>!(dirtyById.get(row.id)?.action==="delete"));for(const row of localRows){const q=dirtyById.get(row.id);if(q&&q.action!=="delete"&&!serverRows.some(r=>r.id===row.id))serverRows.push(row);}next[local]=serverRows;await offlineReplaceAll(local,serverRows);}setData(current=>({...current,...next}));return true;}catch(e){console.warn("[Sync] pull failed",e);return false;}}
export function registerSyncHandlers(setData,queueRef){_globalSetData=setData;_globalQueueRef=queueRef;}
export function triggerImmediateSync(){if(_globalSetData&&_globalQueueRef)pushSyncQueue(_globalQueueRef.current||[],_globalSetData).catch(()=>{});}
export function setupRealtimeSync(uid,setData){if(!uid)return()=>{};const channels=SYNC_TABLES.map(table=>{let channel=supabase.channel(`powermate-${uid}-${table}`);channel=channel.on("postgres_changes",{event:"*",schema:"public",table},payload=>{const local=localStoreName(table);if(table==="team_notifications"&&payload.new?.to_user_id!==uid)return;const teamId=payload.new?.team_id??payload.old?.team_id;if(TEAM_TABLES.has(table)&&!teamId)return;const dirty=dirtyQueueForTable(table);const id=payload.new?.id||payload.old?.id;if(dirty.some(q=>q.data?.id===id))return;setData(current=>{const rows=current[local]||[];if(payload.eventType==="DELETE")return{...current,[local]:rows.filter(r=>r.id!==payload.old?.id)};const row=payload.new;if(!row?.id)return current;const idx=rows.findIndex(r=>r.id===row.id);return{...current,[local]:idx>=0?rows.map((r,i)=>i===idx?row:r):[row,...rows]};});});channel.subscribe();return channel;});const timer=setInterval(()=>{if(document.visibilityState!=="hidden"&&navigator.onLine)pullFromSupabase(uid,setData).catch(()=>{});},RECONCILE_MS);return()=>{clearInterval(timer);channels.forEach(c=>supabase.removeChannel(c));};}
