// Synthetic team data with the same volumes and shapes as production (no real records).
const crypto = require("crypto");
const uuid = () => crypto.randomUUID();
const day = n => { const d = new Date(); d.setDate(d.getDate() - n); return d.toISOString().slice(0, 10); };
module.exports = function synth() {
  const TEAM = "4c36881d-695c-467b-902c-45203a86a078";
  const FIELD = "dc4e613a-ef56-472a-b700-66365f67f258", GREG = "f16f3dd1-c87c-4066-8a38-750d7bc31d65", ADMIN = "431dcb72-ea3f-43ed-9f73-74384e862300";
  const regions = ["Gauteng", "Limpopo", "Mpumalanga", "North West", "Northern Cape", null];
  const stages = ["Contacted", "Dormant", "New Lead", "Quoted"];
  const clients = Array.from({ length: 39 }, (_, i) => ({ id: uuid(), user_id: i < 37 ? FIELD : GREG, company: `Sim Mine ${i % 30}`, division: i % 3 ? "jacks" : "ausco,tyres", contact: `Buyer ${i}`, phone: `08200000${String(i).padStart(2, "0")}`, email: `buyer${i}@example.com`, location: `Site ${i}`, notes: i % 4 ? "" : "Long note ".repeat(20), created_at: day(60 - i) + "T08:00:00", updated_at: day(10) + "T08:00:00Z", branch: `Shaft ${i % 3}`, stage: stages[i % 4 === 1 ? 1 : i % 4], sync_status: "synced", auto_created: false, source: "manual", team_id: TEAM, assigned_to_user_id: null, assigned_to: null, category: regions[i % 6], last_contacted: day(i), interactions: i % 5 ? [] : [{ type: "call", date: day(i), note: "Spoke" }] }));
  const contacts = Array.from({ length: 59 }, (_, i) => ({ id: uuid(), user_id: i < 57 ? FIELD : GREG, name: `Contact ${i}`, company: clients[i % 39].company, title: "Engineer", email: `c${i}@example.com`, phone: `07100000${String(i).padStart(2, "0")}`, met_at: "Expo", met_date: day(i), notes: "", card_photo_url: i === 0 ? `https://hrqzqyfvbfzrfnuxovvr.supabase.co/storage/v1/object/public/powermate-media/${FIELD}/contacts/card-sim.jpg` : null, status: "lead", client_id: i % 3 ? clients[i % 39].id : null, sync_status: "synced", created_at: day(i) + "T08:00:00Z", updated_at: day(i) + "T08:00:00Z", team_id: i < 51 ? TEAM : null, assigned_to_user_id: null, assigned_to: null, category: [null, "Electra Mining 2026", "Ghana EXPO 2026", "Phalaborwa"][i % 4] }));
  const quotes = Array.from({ length: 4 }, (_, i) => ({ id: uuid(), user_id: FIELD, client_id: clients[i].id, client_name: clients[i].company, quote_number: `Q-${100 + i}`, description: "Hydraulic service", value: 376683 - i * 1000, status: "Pending", sent_date: day(5 + i), follow_up_date: day(-2), flagged: false, notes: "", created_at: day(5 + i) + "T08:00:00Z", sync_status: "synced", job_card_number: null, expiry_date: day(-25), line_items: JSON.stringify([{ description: "Service kit", qty: 1, unitPrice: 376683 - i * 1000 }]), source_email_id: null, pdf_url: null, attachments: [], parse_confidence: null, client_candidate_pdf: null, client_candidate_email: null, client_confirmed: true, track: null, team_id: TEAM, vat_inclusive: true, assigned_to_user_id: null, updated_at: day(5) + "T08:00:00Z", source: "manual" }));
  const reminders = ["15_before", "morning", "30_min", "1h_before", "morning"];
  const followups = Array.from({ length: 15 }, (_, i) => ({ id: uuid(), user_id: i < 14 ? FIELD : GREG, title: `Follow up ${i}`, created_at: day(3) + "T08:00:00Z", client: clients[i].company, date: day(-i + 1), time: i < 4 ? "" : "10:30", reminder: reminders[i % 5], completed: i % 6 === 5, sync_status: "synced", quote_id: i === 0 ? quotes[0].id : null, auto_generated: i === 0, client_id: clients[i].id, branch: null, notes: "", linked_note_id: null, team_id: TEAM, assigned_to_user_id: null, assigned_to: null, notified_at: null, contact_id: null, updated_at: day(3) + "T08:00:00Z", from_user_id: null, linked_breakdown_id: null, to_user_id: null, sync_pending_quote_id: null, sync_pending_client_id: null, sync_pending_note_id: null, sync_pending_team_id: null }));
  const notes = Array.from({ length: 14 }, (_, i) => ({ id: uuid(), user_id: i < 12 ? FIELD : GREG, client: clients[i].company, note: `Visit note ${i}`, urgency: i < 2 ? "Critical" : "Normal", resolve_by: day(-3), resolved: i % 4 === 0, resolved_at: null, last_escalated: null, media: [], sync_status: "synced", created_at: day(i) + "T08:00:00Z", linked_contact_ids: [], client_id: i < 2 ? uuid() : clients[i].id, team_id: TEAM, assigned_to_user_id: null, assigned_to: null, category: null, visit_date: day(i), updated_at: day(i) + "T08:00:00Z" }));
  const jobs = [{ id: uuid(), user_id: FIELD, team_id: TEAM, client_id: clients[0].id, quote_id: quotes[0].id, job_number: "JOB-2026-0001", title: "Hydraulic service", description: "Service", status: "in_progress", priority: "normal", scheduled_date: day(0), scheduled_time: "09:00:00", location: "Shaft 1", assigned_to_user_id: null, assigned_to: null, technician_notes: "", work_done: "", parts_used: [], photos: [], started_at: day(0) + "T07:00:00Z", completed_at: null, created_at: day(1) + "T08:00:00Z", updated_at: day(1) + "T08:00:00Z", sync_status: "synced" }];
  const members = [[FIELD, "christo@pwrstart.com", "Christo"], [GREG, "greg@pwrstart.com", "Greg"], [ADMIN, "cvanjaarsveld2@icloud.com", "Christo van Jaarsveld"]];
  const company_documents = Array.from({ length: 7 }, (_, i) => ({ id: uuid(), user_id: FIELD, name: `Document ${i}`, category: i === 0 ? "Company Profile" : "Brochure", file_url: `${FIELD}/${uuid()}.pdf`, file_name: `doc${i}.pdf`, file_size: 250000, created_at: day(20) + "T08:00:00Z", updated_at: day(20) + "T08:00:00Z", team_id: TEAM }));
  return {
    clients, contacts, quotes, followups, notes, jobs, company_documents,
    team_members: members.map(([u], i) => ({ id: uuid(), team_id: TEAM, user_id: u, role: "admin", can_view_team: false, joined_at: day(80 - i) + "T08:00:00Z" })),
    teams: [{ id: TEAM, name: "Power Works", invite_code: "SIM123", created_at: day(90) + "T08:00:00Z" }],
    users: members.map(([id, email, full_name]) => ({ id, email, role: id === ADMIN ? "admin" : "employee", full_name })),
    push_subscriptions: [],
    _rpc: { current_team_id: TEAM, get_my_effective_role: "admin", get_team_member_emails: members.map(([user_id, email, full_name], i) => ({ user_id, role: "admin", joined_at: day(80 - i) + "T08:00:00Z", email, full_name })) },
  };
};
