import React, { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";
import { supabase } from "./supabase";
import {
  Bell,
  BriefcaseBusiness,
  CalendarCheck,
  CalendarDays,
  Camera,
  ChevronRight,
  ClipboardList,
  FileText,
  Home,
  Mail,
  MapPin,
  Mic,
  Phone,
  Plus,
  Search,
  Trash2,
  Upload,
  Users,
  Wrench,
  X,
} from "lucide-react";

// ─── Supabase upload helper ───────────────────────────────────────────────────
const uploadFile = async (file) => {
  try {
    const cleanFileName = file.name.replace(/[^a-zA-Z0-9._-]/g, "_");
    const fileName = `${Date.now()}-${cleanFileName}`;

    const { error } = await supabase.storage
      .from("powermate-files")
      .upload(fileName, file, {
        cacheControl: "3600",
        upsert: false,
      });

    if (error) {
      alert("Upload error: " + error.message);
      return null;
    }

    const { data } = supabase.storage
      .from("powermate-files")
      .getPublicUrl(fileName);

    return data.publicUrl;
  } catch (err) {
    alert("Upload failed: " + err.message);
    console.error("Upload crashed:", err);
    return null;
  }
};

// ─── Constants ────────────────────────────────────────────────────────────────
const APP_NAME = "PowerMate";
const STORAGE_KEY = "powermate_app_data_v1";

const blankSettings = {
  companyName: "",
  repName: "",
  defaultReminderTime: "08:00",
  followUpReminderDays: "7",
  pdfFooterNote: "Generated by PowerMate",
};

const starterData = {
  clients: [],
  planList: [],
  followUps: [],
  documents: [],
  serviceReports: [],
  salesReports: [],
  settings: blankSettings,
};

// ─── Utilities ────────────────────────────────────────────────────────────────
function todayISO() {
  return new Date().toISOString().slice(0, 10);
}

function niceDate(date = new Date()) {
  return date.toLocaleDateString("en-GB", {
    weekday: "long",
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

function makeId(prefix = "id") {
  return `${prefix}_${Date.now()}_${Math.random().toString(36).slice(2, 8)}`;
}

function safeLoad() {
  try {
    const saved = localStorage.getItem(STORAGE_KEY);
    if (!saved) return starterData;
    const parsed = JSON.parse(saved);
    return {
      ...starterData,
      ...parsed,
      settings: { ...blankSettings, ...(parsed.settings || {}) },
      clients: parsed.clients || [],
      planList: parsed.planList || [],
      followUps: parsed.followUps || [],
      documents: parsed.documents || [],
      serviceReports: parsed.serviceReports || [],
      salesReports: parsed.salesReports || [],
    };
  } catch (error) {
    console.error("Could not load saved PowerMate data", error);
    return starterData;
  }
}

function daysSince(dateString) {
  if (!dateString) return 999;
  const oldDate = new Date(`${dateString}T12:00:00`);
  const today = new Date(`${todayISO()}T12:00:00`);
  return Math.max(0, Math.floor((today - oldDate) / 86400000));
}

async function filesToStoredFiles(fileList, clientId = "") {
  const files = Array.from(fileList || []);
  const converted = [];
  for (const file of files) {
    const publicUrl = await uploadFile(file);
    if (!publicUrl) continue;
    converted.push({
      id: makeId("file"),
      name: file.name,
      type: file.type || "File",
      size: file.size,
      clientId,
      date: todayISO(),
      dataUrl: publicUrl,
      storage: "supabase",
    });
  }
  return converted;
}

// ─── Base UI components ───────────────────────────────────────────────────────
function Card({ className = "", children }) {
  return <div className={`bg-white ${className}`}>{children}</div>;
}

function CardContent({ className = "", children }) {
  return <div className={className}>{children}</div>;
}

function Button({ children, className = "", variant = "solid", onClick, type = "button" }) {
  const base = "inline-flex items-center justify-center gap-2 font-semibold transition active:scale-[0.98] disabled:opacity-50";
  const style =
    variant === "outline"
      ? "border border-slate-200 bg-white text-slate-900"
      : variant === "danger"
      ? "bg-red-50 text-red-700"
      : "bg-slate-900 text-white";
  return (
    <button type={type} onClick={onClick} className={`${base} ${style} px-4 py-3 ${className}`}>
      {children}
    </button>
  );
}

function Field({ label, value, onChange, placeholder = "", type = "text", multiline = false }) {
  return (
    <div>
      <label className="mb-1 block text-sm font-semibold text-slate-800">{label}</label>
      {multiline ? (
        <textarea
          rows={4}
          value={value || ""}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-base outline-none focus:border-slate-500"
        />
      ) : (
        <input
          type={type}
          value={value || ""}
          onChange={(e) => onChange(e.target.value)}
          placeholder={placeholder}
          className="w-full rounded-2xl border border-slate-200 bg-white p-4 text-base outline-none focus:border-slate-500"
        />
      )}
    </div>
  );
}

function BigAction({ icon: Icon, title, subtitle, onClick }) {
  return (
    <button
      onClick={onClick}
      className="flex w-full items-center gap-4 rounded-3xl bg-white p-4 text-left shadow-sm transition hover:scale-[1.01] hover:shadow-md"
    >
      <div className="rounded-2xl bg-slate-900 p-4 text-white">
        <Icon size={26} />
      </div>
      <div className="flex-1">
        <p className="text-lg font-bold text-slate-900">{title}</p>
        <p className="text-sm text-slate-500">{subtitle}</p>
      </div>
      <ChevronRight className="text-slate-400" />
    </button>
  );
}

function BottomTab({ icon: Icon, label, active, onClick }) {
  return (
    <button
      onClick={onClick}
      className={`flex flex-col items-center justify-center gap-1 rounded-2xl px-2 py-2 text-xs font-medium transition ${
        active ? "bg-slate-900 text-white" : "text-slate-500"
      }`}
    >
      <Icon size={20} />
      {label}
    </button>
  );
}

function EmptyState({ title, text }) {
  return (
    <div className="rounded-3xl bg-white p-5 text-center text-sm text-slate-500 shadow-sm">
      <p className="font-bold text-slate-900">{title}</p>
      <p className="mt-1">{text}</p>
    </div>
  );
}

// ─── Screens ──────────────────────────────────────────────────────────────────
function HomeScreen({ go, data, setData }) {
  const [viewMode, setViewMode] = useState("main");
  const [editingId, setEditingId] = useState(null);

  const dueFollowUps = data.followUps.filter(
    (item) => !item.completed && item.dueDate && item.dueDate <= todayISO()
  );
  const staleClients = data.clients.filter((client) => daysSince(client.lastConversation) >= 7);

  useEffect(() => {
    if (!("Notification" in window)) return;
    if (Notification.permission === "default") Notification.requestPermission();
  }, []);

  useEffect(() => {
    if (!("Notification" in window)) return;
    if (Notification.permission !== "granted") return;
    if (dueFollowUps.length > 0) {
      new Notification(`${APP_NAME} follow-up reminder`, {
        body: `You have ${dueFollowUps.length} client follow-up(s) due.`,
      });
    }
  }, []);

  const updatePlanItem = (id, field, value) => {
    setData((current) => ({
      ...current,
      planList: current.planList.map((item) => (item.id === id ? { ...item, [field]: value } : item)),
    }));
  };

  const deletePlanItem = (id) => {
    setData((current) => ({
      ...current,
      planList: current.planList.filter((item) => item.id !== id),
    }));
  };

  const updateFollowUp = (id, field, value) => {
    setData((current) => ({
      ...current,
      followUps: current.followUps.map((item) => (item.id === id ? { ...item, [field]: value } : item)),
    }));
  };

  if (viewMode === "today") {
    return (
      <div className="space-y-5">
        <Button variant="outline" className="rounded-2xl" onClick={() => setViewMode("main")}>← Back</Button>
        <h1 className="text-2xl font-bold text-slate-900">Today's jobs / visits</h1>
        {data.planList.length === 0 && <EmptyState title="No items planned" text="Add jobs and visits from the Calendar screen." />}
        {data.planList.map((item) => (
          <Card key={item.id} className="rounded-3xl shadow-sm">
            <CardContent className="space-y-3 p-4">
              <Field label="Time" type="time" value={item.time} onChange={(v) => updatePlanItem(item.id, "time", v)} />
              <Field label="Title" value={item.title} onChange={(v) => updatePlanItem(item.id, "title", v)} />
              <Field label="Client" value={item.client} onChange={(v) => updatePlanItem(item.id, "client", v)} />
              <Field label="Location" value={item.location} onChange={(v) => updatePlanItem(item.id, "location", v)} />
              <Field label="Type" value={item.type} onChange={(v) => updatePlanItem(item.id, "type", v)} />
              <Button variant="danger" className="w-full rounded-2xl" onClick={() => deletePlanItem(item.id)}>Delete item</Button>
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  if (viewMode === "followups") {
    return (
      <div className="space-y-5">
        <Button variant="outline" className="rounded-2xl" onClick={() => setViewMode("main")}>← Back</Button>
        <h1 className="text-2xl font-bold text-slate-900">Follow-ups</h1>
        {data.followUps.length === 0 && <EmptyState title="No follow-ups yet" text="Create one from a client profile or conversation." />}
        {data.followUps.map((item) => (
          <Card key={item.id} className="rounded-3xl shadow-sm">
            <CardContent className="space-y-3 p-4">
              <h2 className="text-lg font-bold text-slate-900">{item.clientName || "Follow-up"}</h2>
              <Field label="Due date" type="date" value={item.dueDate} onChange={(v) => updateFollowUp(item.id, "dueDate", v)} />
              <Field label="Status" value={item.status} onChange={(v) => updateFollowUp(item.id, "status", v)} />
              <Field label="Outcome" multiline value={item.outcome} onChange={(v) => updateFollowUp(item.id, "outcome", v)} />
              <label className="flex items-center justify-between rounded-2xl bg-slate-50 p-4 text-sm font-semibold">
                Completed
                <input
                  type="checkbox"
                  checked={!!item.completed}
                  onChange={(e) => updateFollowUp(item.id, "completed", e.target.checked)}
                  className="h-5 w-5 accent-slate-900"
                />
              </label>
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="rounded-3xl bg-slate-900 p-5 text-white shadow-sm">
        <p className="text-sm text-slate-300">Today, {niceDate()}</p>
        <h1 className="mt-1 text-3xl font-bold">Your day is ready</h1>
        <p className="mt-2 text-slate-300">
          You have {data.planList.length} planned items, {dueFollowUps.length} follow-up due, and {staleClients.length} clients needing attention.
        </p>
      </div>

      <div className="grid grid-cols-2 gap-3">
        <button onClick={() => setViewMode("today")} className="text-left">
          <Card className="rounded-3xl shadow-sm">
            <CardContent className="p-4">
              <p className="text-sm text-slate-500">Today</p>
              <p className="text-3xl font-bold text-slate-900">{data.planList.length}</p>
              <p className="text-sm text-slate-500">jobs / visits</p>
            </CardContent>
          </Card>
        </button>
        <button onClick={() => setViewMode("followups")} className="text-left">
          <Card className="rounded-3xl shadow-sm">
            <CardContent className="p-4">
              <p className="text-sm text-slate-500">Follow-ups</p>
              <p className="text-3xl font-bold text-slate-900">{dueFollowUps.length}</p>
              <p className="text-sm text-slate-500">due now</p>
            </CardContent>
          </Card>
        </button>
      </div>

      <div className="space-y-3">
        <h2 className="text-lg font-bold text-slate-900">Quick actions</h2>
        <BigAction icon={CalendarDays} title="Calendar" subtitle="View, edit and link your calendar" onClick={() => go("Calendar")} />
        <BigAction icon={Plus} title="Add conversation" subtitle="Log a call, WhatsApp, email, or visit" onClick={() => go("QuickAdd")} />
        <BigAction icon={Wrench} title="Create service report" subtitle="Fault, work done, parts, photos and PDF" onClick={() => go("Service")} />
        <BigAction icon={Camera} title="Take photos / upload document" subtitle="Attach evidence to a client or job" onClick={() => go("Documents")} />
      </div>

      <Card className="rounded-3xl shadow-sm">
        <CardContent className="p-4">
          <div className="mb-3 flex items-center justify-between">
            <h2 className="text-lg font-bold text-slate-900">Next up</h2>
            <Button variant="outline" className="rounded-xl" onClick={() => go("Calendar")}>View all</Button>
          </div>
          {data.planList.length === 0 && <p className="text-sm text-slate-500">Nothing planned yet.</p>}
          <div className="space-y-3">
            {data.planList.map((item) => (
              <div key={item.id} className="rounded-2xl bg-slate-50 p-3">
                {editingId === item.id ? (
                  <div className="space-y-2">
                    <input type="time" value={item.time || ""} onChange={(e) => updatePlanItem(item.id, "time", e.target.value)} className="w-full rounded-xl border p-2" />
                    <input value={item.title || ""} onChange={(e) => updatePlanItem(item.id, "title", e.target.value)} className="w-full rounded-xl border p-2" />
                    <input value={item.client || ""} onChange={(e) => updatePlanItem(item.id, "client", e.target.value)} className="w-full rounded-xl border p-2" />
                    <input value={item.location || ""} onChange={(e) => updatePlanItem(item.id, "location", e.target.value)} className="w-full rounded-xl border p-2" />
                    <input value={item.type || ""} onChange={(e) => updatePlanItem(item.id, "type", e.target.value)} className="w-full rounded-xl border p-2" />
                    <Button className="w-full rounded-2xl" onClick={() => setEditingId(null)}>Done</Button>
                  </div>
                ) : (
                  <div className="flex gap-3">
                    <div className="w-16 rounded-2xl bg-white p-2 text-center shadow-sm">
                      <p className="text-sm font-bold text-slate-900">{item.time || "--:--"}</p>
                      <p className="text-xs text-slate-500">{item.type}</p>
                    </div>
                    <div className="flex-1">
                      <p className="font-semibold text-slate-900">{item.title}</p>
                      <p className="text-sm text-slate-500">{item.client}</p>
                      <p className="mt-1 flex items-center gap-1 text-xs text-slate-500"><MapPin size={13} /> {item.location}</p>
                    </div>
                    <Button variant="outline" className="rounded-xl" onClick={() => setEditingId(item.id)}>Edit</Button>
                  </div>
                )}
              </div>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function QuickAddScreen({ data, setData, go }) {
  const [selectedClientId, setSelectedClientId] = useState("");
  const [newClient, setNewClient] = useState({ company: "", division: "", contact: "", phone: "", email: "", location: "" });
  const [conversationNote, setConversationNote] = useState("");
  const [nextFollowUp, setNextFollowUp] = useState("");
  const [recording, setRecording] = useState(false);
  const [mediaRecorder, setMediaRecorder] = useState(null);
  const [audioDataUrl, setAudioDataUrl] = useState("");
  const [audioError, setAudioError] = useState("");
  const [mediaFiles, setMediaFiles] = useState([]);
  const [uploading, setUploading] = useState(false);

  const selectedClient = data.clients.find((c) => c.id === selectedClientId);

  const startRecording = async () => {
    try {
      setAudioError("");
      if (!navigator.mediaDevices?.getUserMedia || typeof MediaRecorder === "undefined") {
        setAudioError("Voice recording is not supported on this browser.");
        return;
      }
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const recorder = new MediaRecorder(stream);
      const chunks = [];
      recorder.ondataavailable = (e) => e.data?.size > 0 && chunks.push(e.data);
      recorder.onstop = () => {
        const blob = new Blob(chunks, { type: recorder.mimeType || "audio/webm" });
        const reader = new FileReader();
        reader.onload = () => setAudioDataUrl(reader.result);
        reader.readAsDataURL(blob);
        stream.getTracks().forEach((track) => track.stop());
      };
      recorder.start();
      setMediaRecorder(recorder);
      setRecording(true);
    } catch (err) {
      console.error(err);
      setAudioError("Microphone permission was blocked. Check browser permissions.");
    }
  };

  const stopRecording = () => {
    if (!mediaRecorder || !recording) return;
    mediaRecorder.stop();
    setRecording(false);
    setMediaRecorder(null);
  };

  const handleMediaUpload = async (e) => {
    setUploading(true);
    const stored = await filesToStoredFiles(e.target.files, selectedClientId);
    setMediaFiles((current) => [...current, ...stored]);
    e.target.value = "";
    setUploading(false);
  };

  const saveConversation = () => {
    if (!selectedClientId && !newClient.company.trim()) {
      alert("Please select a client or add a new client name.");
      return;
    }

    let clientId = selectedClientId;
    let clientName = selectedClient?.company || "";

    setData((current) => {
      let clients = current.clients;
      let documents = current.documents;
      let followUps = current.followUps;

      if (!clientId) {
        clientId = makeId("client");
        clientName = newClient.company.trim();
        clients = [
          ...clients,
          {
            id: clientId,
            company: newClient.company.trim(),
            division: newClient.division.trim(),
            contact: newClient.contact.trim(),
            phone: newClient.phone.trim(),
            email: newClient.email.trim(),
            location: newClient.location.trim(),
            status: "New lead",
            value: "",
            notes: "",
            lastConversation: todayISO(),
            nextFollowUp: nextFollowUp || "",
            history: [],
          },
        ];
      }

      const historyEntry = {
        id: makeId("history"),
        date: todayISO(),
        note: conversationNote,
        audioDataUrl,
        fileIds: mediaFiles.map((f) => f.id),
      };

      clients = clients.map((client) =>
        client.id === clientId
          ? {
              ...client,
              lastConversation: todayISO(),
              nextFollowUp: nextFollowUp || client.nextFollowUp || "",
              history: [historyEntry, ...(client.history || [])],
            }
          : client
      );

      documents = [...documents, ...mediaFiles.map((f) => ({ ...f, clientId }))];

      if (nextFollowUp) {
        followUps = [
          ...followUps,
          {
            id: makeId("followup"),
            clientId,
            clientName,
            dueDate: nextFollowUp,
            status: "Open",
            outcome: conversationNote,
            completed: false,
          },
        ];
      }

      return { ...current, clients, documents, followUps };
    });

    setSelectedClientId("");
    setNewClient({ company: "", division: "", contact: "", phone: "", email: "", location: "" });
    setConversationNote("");
    setNextFollowUp("");
    setAudioDataUrl("");
    setMediaFiles([]);
    alert("Conversation saved.");
    go("Clients");
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Add conversation</h1>
        <p className="text-sm text-slate-500">Capture notes, photos, videos and voice notes quickly.</p>
      </div>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-4 p-4">
          <select value={selectedClientId} onChange={(e) => setSelectedClientId(e.target.value)} className="w-full rounded-2xl border border-slate-200 p-4">
            <option value="">+ Add new client / or select existing</option>
            {data.clients.map((client) => (
              <option key={client.id} value={client.id}>
                {client.company} {client.division ? `- ${client.division}` : ""}
              </option>
            ))}
          </select>

          {!selectedClientId && (
            <div className="space-y-3 rounded-2xl bg-slate-50 p-3">
              <Field label="Company" value={newClient.company} onChange={(v) => setNewClient((c) => ({ ...c, company: v }))} placeholder="Example: Mine / Company" />
              <Field label="Division / Site" value={newClient.division} onChange={(v) => setNewClient((c) => ({ ...c, division: v }))} placeholder="Example: Workshop / Shaft 3" />
              <Field label="Contact person" value={newClient.contact} onChange={(v) => setNewClient((c) => ({ ...c, contact: v }))} />
              <Field label="Phone" value={newClient.phone} onChange={(v) => setNewClient((c) => ({ ...c, phone: v }))} />
              <Field label="Email" value={newClient.email} onChange={(v) => setNewClient((c) => ({ ...c, email: v }))} />
              <Field label="Location" value={newClient.location} onChange={(v) => setNewClient((c) => ({ ...c, location: v }))} />
            </div>
          )}

          <Field label="What was discussed?" multiline value={conversationNote} onChange={setConversationNote} placeholder="Notes..." />
          <Field label="Next follow-up date" type="date" value={nextFollowUp} onChange={setNextFollowUp} />

          <div className="grid grid-cols-2 gap-3">
            <Button
              variant="outline"
              className={`rounded-2xl py-6 ${recording ? "border-red-300 bg-red-100 text-red-700" : ""}`}
              onClick={recording ? stopRecording : startRecording}
            >
              <Mic size={18} /> {recording ? "Stop" : "Voice note"}
            </Button>
            <label className={`flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white py-6 font-semibold ${uploading ? "opacity-60 pointer-events-none" : ""}`}>
              <Camera size={18} /> {uploading ? "Uploading…" : "Add photo/video"}
              <input type="file" accept="image/*,video/*" multiple className="hidden" onChange={handleMediaUpload} disabled={uploading} />
            </label>
          </div>

          <div className="rounded-2xl bg-blue-50 p-3 text-xs text-blue-800">
            Photos and videos are uploaded securely to cloud storage via Supabase.
          </div>

          {audioError && <div className="rounded-2xl bg-red-50 p-3 text-sm font-semibold text-red-700">{audioError}</div>}

          {audioDataUrl && (
            <div className="rounded-2xl bg-slate-50 p-3">
              <div className="mb-2 flex items-center justify-between">
                <p className="text-sm font-semibold">Voice note</p>
                <button onClick={() => setAudioDataUrl("")} className="rounded-xl bg-red-100 px-3 py-1 text-xs font-semibold text-red-700">Delete</button>
              </div>
              <audio controls src={audioDataUrl} className="w-full" />
            </div>
          )}

          {mediaFiles.length > 0 && (
            <div className="grid grid-cols-2 gap-3 rounded-2xl bg-slate-50 p-3">
              {mediaFiles.map((file) => (
                <div key={file.id} className="rounded-2xl bg-white p-2">
                  {file.type.startsWith("video/") ? (
                    <video controls src={file.dataUrl} className="h-32 w-full rounded-xl object-cover" />
                  ) : (
                    <img src={file.dataUrl} alt={file.name} className="h-32 w-full rounded-xl object-cover" />
                  )}
                  <p className="mt-2 truncate text-xs text-slate-600">{file.name}</p>
                  <button onClick={() => setMediaFiles((current) => current.filter((f) => f.id !== file.id))} className="mt-2 w-full rounded-xl bg-red-50 px-3 py-2 text-xs font-semibold text-red-700">
                    Delete
                  </button>
                </div>
              ))}
            </div>
          )}

          <Button className="w-full rounded-2xl py-6 text-base" onClick={saveConversation}>
            Save conversation
          </Button>
        </CardContent>
      </Card>
    </div>
  );
}

function CalendarScreen({ data, setData }) {
  const [newItem, setNewItem] = useState({ time: "", title: "", client: "", location: "", type: "Follow-up" });

  const addCalendarItem = () => {
    if (!newItem.time || !newItem.title) {
      alert("Please add at least a time and title.");
      return;
    }
    setData((current) => ({ ...current, planList: [...current.planList, { id: makeId("plan"), ...newItem }] }));
    setNewItem({ time: "", title: "", client: "", location: "", type: "Follow-up" });
  };

  const updateCalendarItem = (id, field, value) => {
    setData((current) => ({
      ...current,
      planList: current.planList.map((item) => (item.id === id ? { ...item, [field]: value } : item)),
    }));
  };

  const deleteCalendarItem = (id) => {
    setData((current) => ({ ...current, planList: current.planList.filter((item) => item.id !== id) }));
  };

  const createGoogleCalendarLink = (item) => {
    const title = encodeURIComponent(item.title || "PowerMate item");
    const location = encodeURIComponent(item.location || "");
    const details = encodeURIComponent(`${item.client || ""} - ${item.type || ""}`);
    return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&location=${location}`;
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Calendar</h1>
        <p className="text-sm text-slate-500">Add, edit, delete and send items to Google Calendar.</p>
      </div>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-3 p-4">
          <h2 className="text-lg font-bold text-slate-900">Add new item</h2>
          <Field label="Time" type="time" value={newItem.time} onChange={(v) => setNewItem((i) => ({ ...i, time: v }))} />
          <Field label="Title" value={newItem.title} onChange={(v) => setNewItem((i) => ({ ...i, title: v }))} />
          <select value={newItem.client} onChange={(e) => setNewItem((i) => ({ ...i, client: e.target.value }))} className="w-full rounded-2xl border border-slate-200 p-4">
            <option value="">Select client</option>
            {data.clients.map((c) => (
              <option key={c.id} value={`${c.company}${c.division ? ` - ${c.division}` : ""}`}>
                {c.company} {c.division ? `- ${c.division}` : ""}
              </option>
            ))}
          </select>
          <Field label="Location" value={newItem.location} onChange={(v) => setNewItem((i) => ({ ...i, location: v }))} />
          <select value={newItem.type} onChange={(e) => setNewItem((i) => ({ ...i, type: e.target.value }))} className="w-full rounded-2xl border border-slate-200 p-4">
            <option>Follow-up</option>
            <option>Service</option>
            <option>Sales</option>
            <option>Meeting</option>
            <option>Site visit</option>
          </select>
          <Button className="w-full rounded-2xl py-6" onClick={addCalendarItem}>Add calendar item</Button>
        </CardContent>
      </Card>

      {data.planList.length === 0 && <EmptyState title="No calendar items" text="Add your first job, visit or follow-up above." />}
      <div className="space-y-3">
        {data.planList.map((item) => (
          <Card key={item.id} className="rounded-3xl shadow-sm">
            <CardContent className="space-y-3 p-4">
              <Field label="Time" type="time" value={item.time} onChange={(v) => updateCalendarItem(item.id, "time", v)} />
              <Field label="Title" value={item.title} onChange={(v) => updateCalendarItem(item.id, "title", v)} />
              <Field label="Client" value={item.client} onChange={(v) => updateCalendarItem(item.id, "client", v)} />
              <Field label="Location" value={item.location} onChange={(v) => updateCalendarItem(item.id, "location", v)} />
              <Field label="Type" value={item.type} onChange={(v) => updateCalendarItem(item.id, "type", v)} />
              <a href={createGoogleCalendarLink(item)} target="_blank" rel="noreferrer" className="block">
                <Button className="w-full rounded-2xl"><CalendarDays size={18} /> Add to Google Calendar</Button>
              </a>
              <Button variant="danger" className="w-full rounded-2xl" onClick={() => deleteCalendarItem(item.id)}>Delete item</Button>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}

function ClientsScreen({ data, setData, go }) {
  const [search, setSearch] = useState("");
  const [selectedClientId, setSelectedClientId] = useState(null);
  const [editMode, setEditMode] = useState(false);

  const selectedClient = data.clients.find((client) => client.id === selectedClientId);
  const clientDocuments = data.documents.filter((doc) => doc.clientId === selectedClientId);

  const filtered = useMemo(() => {
    const q = search.toLowerCase();
    return data.clients.filter((client) =>
      `${client.company} ${client.division} ${client.contact} ${client.location}`.toLowerCase().includes(q)
    );
  }, [search, data.clients]);

  const addBlankClient = () => {
    const id = makeId("client");
    setData((current) => ({
      ...current,
      clients: [
        ...current.clients,
        {
          id,
          company: "New Company",
          division: "",
          contact: "",
          phone: "",
          email: "",
          location: "",
          status: "New lead",
          value: "",
          notes: "",
          lastConversation: "",
          nextFollowUp: "",
          history: [],
        },
      ],
    }));
    setSelectedClientId(id);
    setEditMode(true);
  };

  const updateClientField = (field, value) => {
    setData((current) => ({
      ...current,
      clients: current.clients.map((client) =>
        client.id === selectedClientId ? { ...client, [field]: value } : client
      ),
    }));
  };

  const deleteClient = () => {
    if (!selectedClient) return;
    if (!confirm(`Delete ${selectedClient.company}? Documents linked to this client will remain in Documents.`)) return;
    setData((current) => ({
      ...current,
      clients: current.clients.filter((client) => client.id !== selectedClient.id),
      followUps: current.followUps.filter((item) => item.clientId !== selectedClient.id),
    }));
    setSelectedClientId(null);
    setEditMode(false);
  };

  const addFollowUp = () => {
    if (!selectedClient) return;
    setData((current) => ({
      ...current,
      followUps: [
        ...current.followUps,
        {
          id: makeId("followup"),
          clientId: selectedClient.id,
          clientName: selectedClient.company,
          dueDate: selectedClient.nextFollowUp || todayISO(),
          status: "Open",
          outcome: "",
          completed: false,
        },
      ],
    }));
    alert("Follow-up created.");
  };

  if (selectedClient) {
    return (
      <div className="space-y-5">
        <Button variant="outline" className="rounded-2xl" onClick={() => { setSelectedClientId(null); setEditMode(false); }}>
          ← Back to clients
        </Button>
        <Card className="rounded-3xl shadow-sm">
          <CardContent className="space-y-4 p-4">
            <div className="flex items-start justify-between gap-3">
              <div className="flex-1">
                {editMode ? (
                  <Field label="Company" value={selectedClient.company} onChange={(v) => updateClientField("company", v)} />
                ) : (
                  <h1 className="text-2xl font-bold text-slate-900">{selectedClient.company}</h1>
                )}
                {!editMode && selectedClient.division && <p className="text-sm text-slate-500">{selectedClient.division}</p>}
              </div>
              <Button variant="outline" className="rounded-2xl" onClick={() => setEditMode(!editMode)}>
                {editMode ? "Done" : "Edit"}
              </Button>
            </div>

            {editMode && <Field label="Division / Site" value={selectedClient.division} onChange={(v) => updateClientField("division", v)} />}

            <div className="space-y-3 rounded-2xl bg-slate-50 p-3">
              {[
                ["contact", "Contact person"],
                ["phone", "Phone"],
                ["email", "Email"],
                ["location", "Location"],
                ["status", "Status"],
                ["value", "Value"],
              ].map(([field, label]) => (
                <div key={field}>
                  <label className="mb-1 block text-xs font-bold text-slate-500">{label}</label>
                  {editMode ? (
                    <input value={selectedClient[field] || ""} onChange={(e) => updateClientField(field, e.target.value)} className="w-full rounded-2xl border border-slate-200 bg-white p-3 text-sm" />
                  ) : (
                    <p className="text-sm text-slate-700">{selectedClient[field] || "-"}</p>
                  )}
                </div>
              ))}
            </div>

            <div className="rounded-2xl bg-slate-50 p-3">
              <p className="text-sm font-semibold text-slate-800">Notes</p>
              {editMode ? (
                <textarea rows={4} value={selectedClient.notes || ""} onChange={(e) => updateClientField("notes", e.target.value)} className="mt-2 w-full rounded-2xl border border-slate-200 bg-white p-3 text-sm" />
              ) : (
                <p className="mt-1 whitespace-pre-wrap text-sm text-slate-600">{selectedClient.notes || "No notes yet."}</p>
              )}
            </div>

            <div className="grid grid-cols-3 gap-2">
              <a href={`tel:${selectedClient.phone || ""}`} className="block">
                <Button variant="outline" className="w-full rounded-2xl"><Phone size={16} /></Button>
              </a>
              <a href={`mailto:${selectedClient.email || ""}`} className="block">
                <Button variant="outline" className="w-full rounded-2xl"><Mail size={16} /></Button>
              </a>
              <Button className="rounded-2xl" onClick={() => go("QuickAdd")}>Add entry</Button>
            </div>

            <div className="grid grid-cols-2 gap-2">
              <Button variant="outline" className="rounded-2xl" onClick={addFollowUp}>Add follow-up</Button>
              <Button variant="danger" className="rounded-2xl" onClick={deleteClient}>
                <Trash2 size={16} /> Delete client
              </Button>
            </div>

            <div className="space-y-2">
              <h2 className="text-lg font-bold text-slate-900">Client dates</h2>
              <Field label="Last conversation" type="date" value={selectedClient.lastConversation} onChange={(v) => updateClientField("lastConversation", v)} />
              <Field label="Next follow-up" type="date" value={selectedClient.nextFollowUp} onChange={(v) => updateClientField("nextFollowUp", v)} />
            </div>

            <div>
              <h2 className="mb-2 text-lg font-bold text-slate-900">Client history</h2>
              {(selectedClient.history || []).length === 0 && <p className="text-sm text-slate-500">No history yet.</p>}
              <div className="space-y-2">
                {(selectedClient.history || []).map((entry) => (
                  <div key={entry.id} className="rounded-2xl bg-slate-50 p-3">
                    <p className="text-xs font-bold text-slate-500">{entry.date}</p>
                    <p className="mt-1 whitespace-pre-wrap text-sm text-slate-700">{entry.note}</p>
                    {entry.audioDataUrl && <audio controls src={entry.audioDataUrl} className="mt-2 w-full" />}
                  </div>
                ))}
              </div>
            </div>

            <div>
              <h2 className="mb-2 text-lg font-bold text-slate-900">Linked files</h2>
              {clientDocuments.length === 0 && <p className="text-sm text-slate-500">No linked files yet.</p>}
              <div className="grid grid-cols-2 gap-3">
                {clientDocuments.map((doc) => (
                  <div key={doc.id} className="rounded-2xl bg-slate-50 p-2">
                    {doc.type.startsWith("image/") ? (
                      <img src={doc.dataUrl} alt={doc.name} className="h-28 w-full rounded-xl object-cover" />
                    ) : doc.type.startsWith("video/") ? (
                      <video controls src={doc.dataUrl} className="h-28 w-full rounded-xl object-cover" />
                    ) : (
                      <div className="flex h-28 items-center justify-center rounded-xl bg-white"><FileText /></div>
                    )}
                    <p className="mt-2 truncate text-xs text-slate-600">{doc.name}</p>
                  </div>
                ))}
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div className="flex items-start justify-between gap-3">
        <div>
          <h1 className="text-2xl font-bold text-slate-900">Clients</h1>
          <p className="text-sm text-slate-500">Company, division, contacts, history and files.</p>
        </div>
        <Button className="rounded-2xl" onClick={addBlankClient}><Plus size={18} /> Add</Button>
      </div>

      <div className="flex items-center gap-2 rounded-3xl bg-white p-3 shadow-sm">
        <Search size={20} className="text-slate-400" />
        <input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Search client, division or contact" className="w-full bg-transparent p-2 text-base outline-none" />
      </div>

      {data.clients.length === 0 && <EmptyState title="No clients yet" text="Tap Add to create your first client." />}

      <div className="space-y-3">
        {filtered.map((client) => (
          <button key={client.id} onClick={() => setSelectedClientId(client.id)} className="w-full text-left">
            <Card className="rounded-3xl shadow-sm">
              <CardContent className="p-4">
                <div className="flex items-start justify-between gap-3">
                  <div>
                    <h2 className="text-lg font-bold text-slate-900">{client.company}</h2>
                    <p className="text-sm text-slate-500">{client.division || "No division/site"}</p>
                    <p className="mt-1 text-xs text-slate-500">{client.contact || "No contact person"}</p>
                  </div>
                  <ChevronRight className="text-slate-400" />
                </div>
              </CardContent>
            </Card>
          </button>
        ))}
      </div>
    </div>
  );
}

function ServiceScreen({ data, setData }) {
  const [report, setReport] = useState({ clientId: "", machine: "", fault: "", workDone: "", partsUsed: "", technician: "" });
  const [serviceFiles, setServiceFiles] = useState([]);
  const [uploading, setUploading] = useState(false);

  const selectedClient = data.clients.find((c) => c.id === report.clientId);

  const handleServiceFiles = async (e) => {
    setUploading(true);
    const stored = await filesToStoredFiles(e.target.files, report.clientId);
    setServiceFiles((current) => [...current, ...stored]);
    e.target.value = "";
    setUploading(false);
  };

  const saveReport = () => {
    const savedReport = {
      id: makeId("service"),
      date: todayISO(),
      ...report,
      clientName: selectedClient?.company || "",
      fileIds: serviceFiles.map((f) => f.id),
    };
    setData((current) => ({
      ...current,
      serviceReports: [savedReport, ...current.serviceReports],
      documents: [...current.documents, ...serviceFiles],
    }));
    createPDF(savedReport, serviceFiles, data.settings);
    setReport({ clientId: "", machine: "", fault: "", workDone: "", partsUsed: "", technician: "" });
    setServiceFiles([]);
  };

  const createPDF = (savedReport, files, settings) => {
    const printWindow = window.open("", "_blank");
    if (!printWindow) {
      alert("Popup blocked. Allow popups to create PDF.");
      return;
    }
    const esc = (value) =>
      String(value || "").replace(/[&<>'"]/g, (m) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#039;", '"': "&quot;" }[m]));

    printWindow.document.write(`
      <html>
        <head>
          <title>PowerMate Service Report</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 30px; color: #111827; }
            h1 { border-bottom: 2px solid #111827; padding-bottom: 10px; }
            .section { margin-bottom: 18px; }
            .label { font-weight: bold; }
            img { max-width: 100%; margin-top: 10px; border-radius: 10px; }
            .footer { margin-top: 40px; font-size: 12px; color: #6b7280; }
          </style>
        </head>
        <body>
          <h1>PowerMate Service Report</h1>
          <div class="section"><span class="label">Company:</span> ${esc(settings.companyName)}</div>
          <div class="section"><span class="label">Date:</span> ${esc(savedReport.date)}</div>
          <div class="section"><span class="label">Client / Site:</span> ${esc(savedReport.clientName)}</div>
          <div class="section"><span class="label">Machine / Equipment:</span> ${esc(savedReport.machine)}</div>
          <div class="section"><span class="label">Technician:</span> ${esc(savedReport.technician)}</div>
          <div class="section"><span class="label">Fault Found:</span><br/>${esc(savedReport.fault).replace(/\n/g, "<br/>")}</div>
          <div class="section"><span class="label">Work Done:</span><br/>${esc(savedReport.workDone).replace(/\n/g, "<br/>")}</div>
          <div class="section"><span class="label">Parts Used:</span><br/>${esc(savedReport.partsUsed).replace(/\n/g, "<br/>")}</div>
          <h2>Attached Images</h2>
          ${files.map((file) => file.type.startsWith("image/") ? `<div><p>${esc(file.name)}</p><img src="${file.dataUrl}" /></div>` : `<p>${esc(file.name)}</p>`).join("")}
          <div class="footer">${esc(settings.pdfFooterNote)}</div>
          <script>window.onload = function(){ window.print(); }</script>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Service report</h1>
        <p className="text-sm text-slate-500">Complete the report and create a PDF.</p>
      </div>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-4 p-4">
          <select value={report.clientId} onChange={(e) => setReport((r) => ({ ...r, clientId: e.target.value }))} className="w-full rounded-2xl border border-slate-200 p-4">
            <option value="">Select client / site</option>
            {data.clients.map((client) => (
              <option key={client.id} value={client.id}>{client.company} {client.division ? `- ${client.division}` : ""}</option>
            ))}
          </select>
          <Field label="Machine / Equipment" value={report.machine} onChange={(v) => setReport((r) => ({ ...r, machine: v }))} />
          <Field label="Technician" value={report.technician} onChange={(v) => setReport((r) => ({ ...r, technician: v }))} />
          <Field label="Fault found" multiline value={report.fault} onChange={(v) => setReport((r) => ({ ...r, fault: v }))} />
          <Field label="Work done" multiline value={report.workDone} onChange={(v) => setReport((r) => ({ ...r, workDone: v }))} />
          <Field label="Parts used" multiline value={report.partsUsed} onChange={(v) => setReport((r) => ({ ...r, partsUsed: v }))} />
          <label className={`flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-slate-200 bg-white py-6 font-semibold ${uploading ? "opacity-60 pointer-events-none" : ""}`}>
            <Upload size={18} /> {uploading ? "Uploading…" : "Add photos / files"}
            <input type="file" accept="image/*,video/*,.pdf,.doc,.docx,.xls,.xlsx" multiple className="hidden" onChange={handleServiceFiles} disabled={uploading} />
          </label>
          {serviceFiles.map((file) => (
            <div key={file.id} className="rounded-2xl bg-slate-50 p-3">
              <p className="text-sm font-semibold">{file.name}</p>
              {file.type.startsWith("image/") && <img src={file.dataUrl} alt={file.name} className="mt-2 max-h-56 w-full rounded-2xl object-cover" />}
              <Button variant="danger" className="mt-2 w-full rounded-xl" onClick={() => setServiceFiles((current) => current.filter((f) => f.id !== file.id))}>
                Delete
              </Button>
            </div>
          ))}
          <Button className="w-full rounded-2xl py-6 text-base" onClick={saveReport}>Save & create PDF</Button>
        </CardContent>
      </Card>
    </div>
  );
}

function DocumentsScreen({ data, setData }) {
  const [clientId, setClientId] = useState("");
  const [uploading, setUploading] = useState(false);

  const handleDocsUpload = async (e) => {
    setUploading(true);
    const stored = await filesToStoredFiles(e.target.files, clientId);
    setData((current) => ({
      ...current,
      documents: [...current.documents, ...stored],
    }));
    e.target.value = "";
    setUploading(false);
  };

  const deleteDoc = (id) => {
    setData((current) => ({ ...current, documents: current.documents.filter((doc) => doc.id !== id) }));
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Documents</h1>
        <p className="text-sm text-slate-500">Upload, view, manage and link files to clients.</p>
      </div>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-3 p-4">
          <select value={clientId} onChange={(e) => setClientId(e.target.value)} className="w-full rounded-2xl border border-slate-200 p-4">
            <option value="">Global document</option>
            {data.clients.map((client) => (
              <option key={client.id} value={client.id}>{client.company} {client.division ? `- ${client.division}` : ""}</option>
            ))}
          </select>
          <label className={`flex cursor-pointer items-center justify-center gap-2 rounded-2xl bg-slate-900 px-4 py-6 font-semibold text-white ${uploading ? "opacity-60 pointer-events-none" : ""}`}>
            <Upload size={18} /> {uploading ? "Uploading…" : "Upload photo, video or document"}
            <input type="file" accept="image/*,video/*,.pdf,.doc,.docx,.xls,.xlsx" multiple className="hidden" onChange={handleDocsUpload} disabled={uploading} />
          </label>
        </CardContent>
      </Card>

      {data.documents.length === 0 && <EmptyState title="No documents uploaded" text="Upload your first file above." />}
      <div className="space-y-3">
        {data.documents.map((doc) => {
          const client = data.clients.find((c) => c.id === doc.clientId);
          return (
            <Card key={doc.id} className="rounded-3xl shadow-sm">
              <CardContent className="space-y-3 p-4">
                <div className="flex items-center gap-3">
                  <div className="rounded-2xl bg-slate-100 p-3 text-slate-700"><FileText size={22} /></div>
                  <div className="flex-1 min-w-0">
                    <p className="truncate font-bold text-slate-900">{doc.name}</p>
                    <p className="text-sm text-slate-500">{client ? `${client.company}${client.division ? ` - ${client.division}` : ""}` : "Global"}</p>
                  </div>
                  <button onClick={() => deleteDoc(doc.id)} className="rounded-xl bg-red-50 p-2 text-red-700"><X size={18} /></button>
                </div>
                {doc.type.startsWith("image/") && <img src={doc.dataUrl} alt={doc.name} className="max-h-72 w-full rounded-2xl object-cover" />}
                {doc.type.startsWith("video/") && <video controls src={doc.dataUrl} className="max-h-72 w-full rounded-2xl" />}
                {doc.type === "application/pdf" && <iframe src={doc.dataUrl} title={doc.name} className="h-96 w-full rounded-2xl border" />}
                {!doc.type.startsWith("image/") && !doc.type.startsWith("video/") && doc.type !== "application/pdf" && (
                  <a href={doc.dataUrl} target="_blank" rel="noreferrer" className="block">
                    <Button className="w-full rounded-2xl">Open document</Button>
                  </a>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>
    </div>
  );
}

function NotificationSettingsScreen() {
  const reminderOptions = [
    "Remind me before meetings",
    "Remind me to follow up on quotes",
    "Alert me when a client has not been contacted for 7 days",
    "Remind me to complete open service reports",
    "Send me a morning summary of my day",
  ];

  const [checked, setChecked] = useState(() => reminderOptions.map((_, i) => i < 4));

  const toggle = (index) => {
    setChecked((current) => current.map((v, i) => (i === index ? !v : v)));
  };

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Calendar & Notifications</h1>
        <p className="text-sm text-slate-500">Connect your calendar and control when PowerMate reminds you.</p>
      </div>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-4 p-4">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-slate-900 p-3 text-white"><CalendarCheck size={24} /></div>
            <div className="flex-1">
              <h2 className="font-bold text-slate-900">Link your calendar</h2>
              <p className="text-sm text-slate-500">Google Calendar links are supported from calendar items.</p>
            </div>
          </div>
          <div className="rounded-2xl bg-slate-50 p-3 text-sm text-slate-600">
            Full live calendar sync will need a backend later. For now, each item can be pushed to Google Calendar manually.
          </div>
        </CardContent>
      </Card>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-4 p-4">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-slate-100 p-3 text-slate-700"><Bell size={24} /></div>
            <div>
              <h2 className="font-bold text-slate-900">Notification rules</h2>
              <p className="text-sm text-slate-500">Choose what PowerMate must remind you about.</p>
            </div>
          </div>
          <div className="space-y-3">
            {reminderOptions.map((option, index) => (
              <label key={option} className="flex cursor-pointer items-center justify-between rounded-2xl bg-slate-50 p-4">
                <span className="pr-4 text-sm font-medium text-slate-800">{option}</span>
                <input
                  type="checkbox"
                  checked={checked[index]}
                  onChange={() => toggle(index)}
                  className="h-6 w-6 accent-slate-900"
                />
              </label>
            ))}
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function InstallAppScreen() {
  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">Install PowerMate</h1>
        <p className="text-sm text-slate-500">Add this app to your phone home screen so it opens like a normal mobile app.</p>
      </div>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-4 p-4">
          <div className="rounded-2xl bg-slate-900 p-4 text-white">
            <h2 className="text-lg font-bold">For iPhone / iPad</h2>
            <p className="mt-1 text-sm text-slate-300">Open in Safari, then use Share → Add to Home Screen.</p>
          </div>
          <ol className="space-y-3 text-sm text-slate-700">
            <li className="rounded-2xl bg-slate-50 p-3"><strong>1.</strong> Open PowerMate in Safari.</li>
            <li className="rounded-2xl bg-slate-50 p-3"><strong>2.</strong> Tap the Share button.</li>
            <li className="rounded-2xl bg-slate-50 p-3"><strong>3.</strong> Tap Add to Home Screen.</li>
            <li className="rounded-2xl bg-slate-50 p-3"><strong>4.</strong> Tap Add.</li>
          </ol>
        </CardContent>
      </Card>
      <Card className="rounded-3xl shadow-sm">
        <CardContent className="space-y-4 p-4">
          <div className="rounded-2xl bg-slate-900 p-4 text-white">
            <h2 className="text-lg font-bold">For Android</h2>
            <p className="mt-1 text-sm text-slate-300">Open in Chrome, then use Install app or Add to Home screen.</p>
          </div>
          <ol className="space-y-3 text-sm text-slate-700">
            <li className="rounded-2xl bg-slate-50 p-3"><strong>1.</strong> Open PowerMate in Chrome.</li>
            <li className="rounded-2xl bg-slate-50 p-3"><strong>2.</strong> Tap the three dots menu.</li>
            <li className="rounded-2xl bg-slate-50 p-3"><strong>3.</strong> Tap Install app or Add to Home screen.</li>
            <li className="rounded-2xl bg-slate-50 p-3"><strong>4.</strong> PowerMate will install on your phone.</li>
          </ol>
        </CardContent>
      </Card>
    </div>
  );
}

function MoreScreen({ go, data, setData }) {
  const [moreView, setMoreView] = useState("main");
  const [salesReport, setSalesReport] = useState({ week: "", visits: "", quotes: "", followUps: "", newLeads: "", summary: "" });

  const saveSalesReport = () => {
    setData((current) => ({
      ...current,
      salesReports: [{ id: makeId("sales"), date: todayISO(), ...salesReport }, ...current.salesReports],
    }));
    setSalesReport({ week: "", visits: "", quotes: "", followUps: "", newLeads: "", summary: "" });
    alert("Sales report saved.");
  };

  const updateSettings = (field, value) => {
    setData((current) => ({ ...current, settings: { ...current.settings, [field]: value } }));
  };

  const exportBackup = () => {
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: "application/json" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `powermate-backup-${todayISO()}.json`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const clearAll = () => {
    if (!confirm("This will delete all local PowerMate data on this device. Continue?")) return;
    localStorage.removeItem(STORAGE_KEY);
    setData(starterData);
  };

  if (moreView === "sales") {
    return (
      <div className="space-y-5">
        <Button variant="outline" className="rounded-2xl" onClick={() => setMoreView("main")}>← Back</Button>
        <h1 className="text-2xl font-bold text-slate-900">Sales reports</h1>
        <Card className="rounded-3xl shadow-sm">
          <CardContent className="space-y-4 p-4">
            <Field label="Week / Date" value={salesReport.week} onChange={(v) => setSalesReport((r) => ({ ...r, week: v }))} placeholder="Example: Week 18 / 03 May 2026" />
            <Field label="Total visits" value={salesReport.visits} onChange={(v) => setSalesReport((r) => ({ ...r, visits: v }))} />
            <Field label="Quotes sent" value={salesReport.quotes} onChange={(v) => setSalesReport((r) => ({ ...r, quotes: v }))} />
            <Field label="Follow-ups completed" value={salesReport.followUps} onChange={(v) => setSalesReport((r) => ({ ...r, followUps: v }))} />
            <Field label="New leads" value={salesReport.newLeads} onChange={(v) => setSalesReport((r) => ({ ...r, newLeads: v }))} />
            <Field label="Weekly summary" multiline value={salesReport.summary} onChange={(v) => setSalesReport((r) => ({ ...r, summary: v }))} />
            <Button className="w-full rounded-2xl py-6" onClick={saveSalesReport}>Save sales report</Button>
          </CardContent>
        </Card>
        {data.salesReports.map((r) => (
          <Card key={r.id} className="rounded-3xl shadow-sm">
            <CardContent className="p-4">
              <p className="font-bold">{r.week || r.date}</p>
              <p className="mt-1 text-sm text-slate-600">{r.summary}</p>
            </CardContent>
          </Card>
        ))}
      </div>
    );
  }

  if (moreView === "settings") {
    return (
      <div className="space-y-5">
        <Button variant="outline" className="rounded-2xl" onClick={() => setMoreView("main")}>← Back</Button>
        <h1 className="text-2xl font-bold text-slate-900">Settings</h1>
        <Card className="rounded-3xl shadow-sm">
          <CardContent className="space-y-4 p-4">
            <Field label="Company name" value={data.settings.companyName} onChange={(v) => updateSettings("companyName", v)} placeholder="Example: CC Innovations (PTY) Ltd" />
            <Field label="Technician / Rep name" value={data.settings.repName} onChange={(v) => updateSettings("repName", v)} placeholder="Your name" />
            <Field label="Default reminder time" value={data.settings.defaultReminderTime} onChange={(v) => updateSettings("defaultReminderTime", v)} />
            <Field label="Follow-up reminder days" value={data.settings.followUpReminderDays} onChange={(v) => updateSettings("followUpReminderDays", v)} />
            <Field label="PDF footer note" multiline value={data.settings.pdfFooterNote} onChange={(v) => updateSettings("pdfFooterNote", v)} />
            <Button variant="outline" className="w-full rounded-2xl py-6" onClick={exportBackup}>Export backup</Button>
            <Button variant="danger" className="w-full rounded-2xl py-6" onClick={clearAll}>Clear all local data</Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="space-y-5">
      <div>
        <h1 className="text-2xl font-bold text-slate-900">More</h1>
        <p className="text-sm text-slate-500">Reports, reminders and settings.</p>
      </div>
      <div className="space-y-3">
        <BigAction icon={Bell} title="Calendar & Notifications" subtitle="Reminder rules and calendar notes" onClick={() => go("Notifications")} />
        <BigAction icon={Home} title="Install on phone" subtitle="Add PowerMate to iOS or Android home screen" onClick={() => go("Install")} />
        <BigAction icon={BriefcaseBusiness} title="Sales reports" subtitle="Weekly visit report and pipeline" onClick={() => setMoreView("sales")} />
        <BigAction icon={ClipboardList} title="Settings" subtitle="PDF templates, backup and account" onClick={() => setMoreView("settings")} />
      </div>
    </div>
  );
}

// ─── Root app ─────────────────────────────────────────────────────────────────
export default function PowerMateApp() {
  const [screen, setScreen] = useState("Home");
  const [data, setData] = useState(() => safeLoad());

  useEffect(() => {
    try {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(data));
    } catch (error) {
      console.error("Could not auto-save PowerMate data", error);
      if (String(error?.name).includes("Quota")) {
        alert("Your browser storage is full. Export a backup before continuing.");
      }
    }
  }, [data]);

  const views = {
    Home: <HomeScreen go={setScreen} data={data} setData={setData} />,
    QuickAdd: <QuickAddScreen data={data} setData={setData} go={setScreen} />,
    Calendar: <CalendarScreen data={data} setData={setData} />,
    Clients: <ClientsScreen data={data} setData={setData} go={setScreen} />,
    Service: <ServiceScreen data={data} setData={setData} />,
    Documents: <DocumentsScreen data={data} setData={setData} />,
    More: <MoreScreen go={setScreen} data={data} setData={setData} />,
    Notifications: <NotificationSettingsScreen />,
    Install: <InstallAppScreen />,
  };

  return (
    <div className="min-h-screen bg-slate-100 text-slate-900">
      <div className="mx-auto max-w-2xl px-4 pb-28 pt-4">
        <header className="mb-4 flex items-center justify-between rounded-3xl bg-white p-4 shadow-sm">
          <div className="flex items-center gap-3">
            <div className="rounded-2xl bg-slate-900 p-3 text-white"><ClipboardList size={22} /></div>
            <div>
              <p className="text-lg font-black leading-tight">PowerMate</p>
              <p className="text-xs text-slate-500">Mobile sales & service assistant</p>
            </div>
          </div>
          <Button className="rounded-2xl" onClick={() => setScreen("QuickAdd")}><Plus size={18} /></Button>
        </header>
        <motion.main key={screen} initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.18 }}>
          {views[screen]}
        </motion.main>
      </div>

      <nav className="fixed bottom-0 left-0 right-0 border-t border-slate-200 bg-white/95 p-2 shadow-lg backdrop-blur">
        <div className="mx-auto grid max-w-2xl grid-cols-5 gap-1">
          <BottomTab icon={Home} label="Home" active={screen === "Home"} onClick={() => setScreen("Home")} />
          <BottomTab icon={Users} label="Clients" active={screen === "Clients"} onClick={() => setScreen("Clients")} />
          <BottomTab icon={Wrench} label="Service" active={screen === "Service"} onClick={() => setScreen("Service")} />
          <BottomTab icon={FileText} label="Docs" active={screen === "Documents"} onClick={() => setScreen("Documents")} />
          <BottomTab icon={Bell} label="More" active={screen === "More"} onClick={() => setScreen("More")} />
        </div>
      </nav>
    </div>
  );
}
