-- RLS performance and role hardening applied to production on 2026-09-19.
drop policy if exists "activities_ins" on public.activities;
create policy "activities_ins" on public.activities for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "breakdown_reports_ins" on public.breakdown_reports;
create policy "breakdown_reports_ins" on public.breakdown_reports for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "clients_ins" on public.clients;
create policy "clients_ins" on public.clients for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "company_documents_ins" on public.company_documents;
create policy "company_documents_ins" on public.company_documents for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "contacts_ins" on public.contacts;
create policy "contacts_ins" on public.contacts for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "custom_faults_ins" on public.custom_faults;
create policy "custom_faults_ins" on public.custom_faults for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "equipment_ins" on public.equipment;
create policy "equipment_ins" on public.equipment for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "expenses_ins" on public.expenses;
create policy "expenses_ins" on public.expenses for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "followups_ins" on public.followups;
create policy "followups_ins" on public.followups for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "leads_ins" on public.leads;
create policy "leads_ins" on public.leads for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "notes_ins" on public.notes;
create policy "notes_ins" on public.notes for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "quotes_ins" on public.quotes;
create policy "quotes_ins" on public.quotes for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "repair_reports_ins" on public.repair_reports;
create policy "repair_reports_ins" on public.repair_reports for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "vehicle_checks_ins" on public.vehicle_checks;
create policy "vehicle_checks_ins" on public.vehicle_checks for insert to authenticated with check (((user_id = (select auth.uid())) AND ((team_id IS NULL) OR (team_id IN (SELECT team_members.team_id FROM public.team_members WHERE team_members.user_id = (select auth.uid()))))));
drop policy if exists "email_quotes_delete_own" on public.email_quotes;
create policy "email_quotes_delete_own" on public.email_quotes for delete to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "email_quotes_select_own" on public.email_quotes;
create policy "email_quotes_select_own" on public.email_quotes for select to authenticated using ((select auth.uid()) = user_id);
drop policy if exists "email_quotes_update_own" on public.email_quotes;
create policy "email_quotes_update_own" on public.email_quotes for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists "team_members_delete" on public.team_members;
create policy "team_members_delete" on public.team_members for delete to authenticated using (((select auth.uid()) = user_id) OR is_team_admin(team_id));
