-- ── Company (tenant) isolation hardening ─────────────────────────────────────
-- Found while preparing the app for more than one company:
--  1. Seven older tables let any user with users.role = 'admin' read and write
--     every company's rows. Now: your own rows, plus rows of people in a company
--     where you can see the whole team (owner, admin, or whole-team view).
--  2. "Shared with me" trusted any notification pointing at any record id, so a
--     user could share another company's record with themselves. Now the share
--     must come from the record's own company (or its owner, if personal).
--  3. The app-wide admin role came from users.role; it is now per company.
--  4. Invite codes were 8 characters; now 12, generated by the server, and
--     regenerated only through an owner-only function.
--  5. Company owners may change only their company's name and invite code
--     (plan, status and billing columns are added later and must not be
--     editable by the company itself).
-- tests/sql/tenant_isolation.sql exercises all of this with two companies.

-- 1 ─────────────────────────────────────────────────────────────────────────
create or replace function private.can_see_user(p_user uuid) returns boolean
language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null and p_user is not null and (
    p_user = auth.uid() or exists (
      select 1 from public.team_members them
       where them.user_id = p_user and private.can_see_team(them.team_id)));
$$;
revoke execute on function private.can_see_user(uuid) from public, anon;
grant execute on function private.can_see_user(uuid) to authenticated;

do $$
declare t text;
begin
  foreach t in array array['conversations','documents','follow_ups','plan_items','sales_reports','service_reports','targets'] loop
    execute format('drop policy if exists %I on public.%I', t || '_access', t);
    execute format(
      'create policy %I on public.%I for all to authenticated
         using (user_id = (select auth.uid()) or private.can_see_user(user_id))
         with check (user_id = (select auth.uid()) or private.can_see_user(user_id))',
      t || '_access', t);
  end loop;
end $$;

-- 2 ─────────────────────────────────────────────────────────────────────────
create or replace function private.shared_with_me(p_type text, p_record_id text, p_team_id uuid, p_owner uuid)
returns boolean language sql stable security definer set search_path = '' as $$
  select auth.uid() is not null and exists (
    select 1 from public.team_notifications n
     where n.to_user_id = auth.uid() and n.record_type = p_type
       and n.record_id::text = p_record_id and not coalesce(n.declined, false)
       and ((p_team_id is not null and n.team_id = p_team_id)
         or (p_team_id is null and n.from_user_id = p_owner)));
$$;
revoke execute on function private.shared_with_me(text, text, uuid, uuid) from public, anon;
grant execute on function private.shared_with_me(text, text, uuid, uuid) to authenticated;

drop policy if exists clients_sel on public.clients;
create policy clients_sel on public.clients for select to authenticated using (
  user_id = (select auth.uid()) or assigned_to_user_id = (select auth.uid())
  or (team_id is not null and private.can_see_team(team_id))
  or private.shared_with_me('client', id::text, team_id, user_id));
drop policy if exists contacts_sel on public.contacts;
create policy contacts_sel on public.contacts for select to authenticated using (
  user_id = (select auth.uid()) or assigned_to_user_id = (select auth.uid())
  or (team_id is not null and private.can_see_team(team_id))
  or private.shared_with_me('contact', id::text, team_id, user_id));
drop policy if exists leads_sel on public.leads;
create policy leads_sel on public.leads for select to authenticated using (
  user_id = (select auth.uid()) or assigned_to_user_id = (select auth.uid())
  or (team_id is not null and private.can_see_team(team_id))
  or private.shared_with_me('lead', id::text, team_id, user_id));
drop policy if exists quotes_sel on public.quotes;
create policy quotes_sel on public.quotes for select to authenticated using (
  user_id = (select auth.uid()) or assigned_to_user_id = (select auth.uid())
  or (team_id is not null and private.can_see_team(team_id))
  or private.shared_with_me('quote', id::text, team_id, user_id));
drop policy if exists followups_sel on public.followups;
create policy followups_sel on public.followups for select to authenticated using (
  user_id = (select auth.uid()) or assigned_to_user_id = (select auth.uid())
  or (team_id is not null and private.can_see_team(team_id))
  or private.shared_with_me('followup', id::text, team_id, user_id));

drop function if exists private.shared_with_me(text, text);

-- 3 ─────────────────────────────────────────────────────────────────────────
create or replace function private.get_my_effective_role() returns text
language sql security definer set search_path = '' as $$
  select case when exists (
      select 1 from public.team_members tm join public.teams t on t.id = tm.team_id
       where tm.user_id = auth.uid() and (tm.role = 'admin' or t.owner_user_id = auth.uid()))
    then 'admin' else 'member' end;
$$;

-- 4 ─────────────────────────────────────────────────────────────────────────
-- 12 characters from 32 unambiguous letters/digits (no 0/O, 1/I): ~1.2e18.
create or replace function private.new_invite_code() returns text
language sql volatile set search_path = '' as $$
  select string_agg(substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', 1 + (get_byte(extensions.gen_random_bytes(1), 0) % 32), 1), '')
    from generate_series(1, 12);
$$;
revoke execute on function private.new_invite_code() from public, anon, authenticated;

alter table public.teams alter column invite_code set default private.new_invite_code();
update public.teams set invite_code = private.new_invite_code() where invite_code is null or length(invite_code) < 12;
alter table public.teams drop constraint if exists teams_invite_code_length;
alter table public.teams add constraint teams_invite_code_length check (invite_code is null or length(invite_code) >= 12);

create or replace function private.regenerate_invite_code(p_team_id uuid) returns text
language plpgsql security definer set search_path = '' as $$
declare v_code text;
begin
  if not private.is_team_owner(p_team_id) then raise exception 'Only the master account can change the invite code'; end if;
  v_code := private.new_invite_code();
  update public.teams set invite_code = v_code where id = p_team_id;
  return v_code;
end $$;
revoke execute on function private.regenerate_invite_code(uuid) from public, anon;
grant execute on function private.regenerate_invite_code(uuid) to authenticated;
create or replace function public.regenerate_invite_code(p_team_id uuid) returns text
language sql security invoker set search_path = '' as $$ select private.regenerate_invite_code(p_team_id); $$;
revoke execute on function public.regenerate_invite_code(uuid) from public, anon;
grant execute on function public.regenerate_invite_code(uuid) to authenticated;

-- 5 ─────────────────────────────────────────────────────────────────────────
revoke update on public.teams from authenticated;
grant update (name) on public.teams to authenticated;
